sqlplus 'sys/World2k!'@oraclepdb as SYSDBA;

---
---Create user for API
---
SHOW con_name;

CREATE USER OT IDENTIFIED BY Orcl1234;

GRANT CONNECT, RESOURCE, DBA TO OT;

exit

sqlplus 'ot/Orcl1234'@oraclepdb

CREATE TABLE ot.keys(id NUMBER GENERATED BY DEFAULT AS IDENTITY, key VARCHAR2(50) NOT NULL, value VARCHAR2(50) NOT NULL, PRIMARY KEY(id));

INSERT INTO ot.keys(key,value) VALUES('98715470130','omelo@osvaldormelo.com');

SELECT * FROM ot.keys WHERE key = '98715470130'AND rownum = 1;

exit

sqlplus 'sys/World2k!'@oraclepoc as sysdba

---Debezium 
ALTER SESSION SET CONTAINER = CDB$ROOT;
alter system set db_recovery_file_dest_size = 4G;
--alter system set db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' scope=spfile;
--alter system set enable_goldengate_replication=true;
shutdown immediate
startup mount
alter database archivelog;
alter database open;
-- Should show "Database log mode: Archive Mode"
archive log list

exit;

ALTER TABLE ot.keys ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ABC/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

ALTER SESSION SET CONTAINER = ABCPDB1;

CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ABC/ABCPDB1/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;


CREATE USER c##dbzuser IDENTIFIED BY dbz DEFAULT TABLESPACE logminer_tbs QUOTA UNLIMITED ON logminer_tbs CONTAINER=ALL;

 GRANT CREATE SESSION TO c##dbzuser CONTAINER=ALL;

  GRANT SET CONTAINER TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$DATABASE to c##dbzuser CONTAINER=ALL;

  GRANT FLASHBACK ANY TABLE TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ANY TABLE TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;

  GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;

  GRANT LOGMINING TO c##dbzuser CONTAINER=ALL;

 

  GRANT CREATE TABLE TO c##dbzuser CONTAINER=ALL;

  GRANT LOCK ANY TABLE TO c##dbzuser CONTAINER=ALL;

  GRANT ALTER ANY TABLE TO c##dbzuser CONTAINER=ALL;

  GRANT CREATE SEQUENCE TO c##dbzuser CONTAINER=ALL;

 

  GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzuser CONTAINER=ALL;

  GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzuser CONTAINER=ALL;

 

  GRANT SELECT ON V_$LOG TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$LOG_HISTORY TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$LOGFILE TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzuser CONTAINER=ALL;

  GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzuser CONTAINER=ALL;