- hosts: localhost
  name: Install AMQ Streams Monitoring Demo
  vars:
    cluster_project: database-migration
    kafka_cluster_name: my-cluster
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    delete_demo: false
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: false
    
    - name: Evaluate {{ cluster_project }} Namespace
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ cluster_project }}"

    # - name: Include Databases role
    #   include_role:
    #     name: databases
    
    # - name: Include AMQ Streams role
    #   include_role:
    #     name: streams

    # - name: Include Monitoring role
    #   include_role:
    #     name: monitoring
    
    - name: Include Debezium
      include_role:
        name: debezium
